[build]
  command = "npm run build"     
  publish = "dist"              

[dev]
  command = "npm start"     
  port = 8888
  publish = "dist"                # Använd samma mapp för förhandsvisning

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
